version: 2.1

jobs:
  # Building and testing the project
  # Useful when a PR is open, for example
  build:
    # Our environment, Python 3.6.8
    docker:
      - image: circleci/python:3.7

    # The steps for our build-and-test
    steps:
      # Get the code
      - checkout

      # Let's install the dependencies
      - run:
          name: Install Dependencies
          command: |
            poetry install

      - run:
          name: Run Pytest, report coverage
          command: |
            poetry run coverage run --omit="/home/circleci/.cache/pypoetry/virtualenvs" -m pytest
            poetry run coveralls
